module.exports = {
  ENVIRONMENT: process.env.NODE_ENV,
  GOOGLE_CLIENTID: process.env.REACT_APP_GOOGLE_OAUTH_CLIENTID,
  IMG_PATH: process.env.REACT_APP_IMG_PATH,
  REST_ENDPOINT: process.env.REACT_APP_API_ENDPOINT,
  STORAGE_KEY: 'NOTESEE_KEY',
  SHOW_GH_CORNER: process.env.REACT_APP_SHOW_GH_CORNER,
};
